// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	data "blog-api/data"

	mock "github.com/stretchr/testify/mock"
)

// IAlbumService is an autogenerated mock type for the IAlbumService type
type IAlbumService struct {
	mock.Mock
}

// CreateAlbum provides a mock function with given fields: album
func (_m *IAlbumService) CreateAlbum(album data.Album) (*data.Album, error) {
	ret := _m.Called(album)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlbum")
	}

	var r0 *data.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Album) (*data.Album, error)); ok {
		return rf(album)
	}
	if rf, ok := ret.Get(0).(func(data.Album) *data.Album); ok {
		r0 = rf(album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(data.Album) error); ok {
		r1 = rf(album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAlbum provides a mock function with given fields: id
func (_m *IAlbumService) DeleteAlbum(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAlbum provides a mock function with given fields: id
func (_m *IAlbumService) GetAlbum(id int) (*data.Album, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbum")
	}

	var r0 *data.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*data.Album, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *data.Album); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlbums provides a mock function with given fields: title, userID, id
func (_m *IAlbumService) GetAlbums(title string, userID int, id int) (*[]data.Album, error) {
	ret := _m.Called(title, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbums")
	}

	var r0 *[]data.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (*[]data.Album, error)); ok {
		return rf(title, userID, id)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *[]data.Album); ok {
		r0 = rf(title, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]data.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(title, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAlbum provides a mock function with given fields: id, album
func (_m *IAlbumService) UpdateAlbum(id int, album data.Album) (*data.Album, error) {
	ret := _m.Called(id, album)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAlbum")
	}

	var r0 *data.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(int, data.Album) (*data.Album, error)); ok {
		return rf(id, album)
	}
	if rf, ok := ret.Get(0).(func(int, data.Album) *data.Album); ok {
		r0 = rf(id, album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(int, data.Album) error); ok {
		r1 = rf(id, album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAlbumService creates a new instance of IAlbumService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAlbumService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAlbumService {
	mock := &IAlbumService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
