// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	data "blog-api/data"

	mock "github.com/stretchr/testify/mock"
)

// ICommentService is an autogenerated mock type for the ICommentService type
type ICommentService struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: album
func (_m *ICommentService) CreateComment(album data.Comment) (*data.Comment, error) {
	ret := _m.Called(album)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 *data.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Comment) (*data.Comment, error)); ok {
		return rf(album)
	}
	if rf, ok := ret.Get(0).(func(data.Comment) *data.Comment); ok {
		r0 = rf(album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(data.Comment) error); ok {
		r1 = rf(album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteComment provides a mock function with given fields: id
func (_m *ICommentService) DeleteComment(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetComment provides a mock function with given fields: id
func (_m *ICommentService) GetComment(id int) (*data.Comment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetComment")
	}

	var r0 *data.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*data.Comment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *data.Comment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetComments provides a mock function with given fields: title, userID, id
func (_m *ICommentService) GetComments(title string, userID int, id int) (*[]data.Comment, error) {
	ret := _m.Called(title, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 *[]data.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (*[]data.Comment, error)); ok {
		return rf(title, userID, id)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *[]data.Comment); ok {
		r0 = rf(title, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]data.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(title, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateComment provides a mock function with given fields: id, album
func (_m *ICommentService) UpdateComment(id int, album data.Comment) (*data.Comment, error) {
	ret := _m.Called(id, album)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 *data.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(int, data.Comment) (*data.Comment, error)); ok {
		return rf(id, album)
	}
	if rf, ok := ret.Get(0).(func(int, data.Comment) *data.Comment); ok {
		r0 = rf(id, album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(int, data.Comment) error); ok {
		r1 = rf(id, album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICommentService creates a new instance of ICommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICommentService {
	mock := &ICommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
