// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	io "io"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IRestClient is an autogenerated mock type for the IRestClient type
type IRestClient struct {
	mock.Mock
}

// NewRequest provides a mock function with given fields: method, url, body, headers
func (_m *IRestClient) NewRequest(method string, url string, body io.Reader, headers map[string]string) (*http.Response, error) {
	ret := _m.Called(method, url, body, headers)

	if len(ret) == 0 {
		panic("no return value specified for NewRequest")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, io.Reader, map[string]string) (*http.Response, error)); ok {
		return rf(method, url, body, headers)
	}
	if rf, ok := ret.Get(0).(func(string, string, io.Reader, map[string]string) *http.Response); ok {
		r0 = rf(method, url, body, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, io.Reader, map[string]string) error); ok {
		r1 = rf(method, url, body, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRestClient creates a new instance of IRestClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRestClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRestClient {
	mock := &IRestClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
