// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	data "blog-api/data"

	mock "github.com/stretchr/testify/mock"
)

// ITodoService is an autogenerated mock type for the ITodoService type
type ITodoService struct {
	mock.Mock
}

// CreateTodo provides a mock function with given fields: album
func (_m *ITodoService) CreateTodo(album data.Todo) (*data.Todo, error) {
	ret := _m.Called(album)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *data.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Todo) (*data.Todo, error)); ok {
		return rf(album)
	}
	if rf, ok := ret.Get(0).(func(data.Todo) *data.Todo); ok {
		r0 = rf(album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(data.Todo) error); ok {
		r1 = rf(album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTodo provides a mock function with given fields: id
func (_m *ITodoService) DeleteTodo(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTodo provides a mock function with given fields: id
func (_m *ITodoService) GetTodo(id int) (*data.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 *data.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*data.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *data.Todo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodos provides a mock function with given fields: title, userID, id
func (_m *ITodoService) GetTodos(title string, userID int, id int) (*[]data.Todo, error) {
	ret := _m.Called(title, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodos")
	}

	var r0 *[]data.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (*[]data.Todo, error)); ok {
		return rf(title, userID, id)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *[]data.Todo); ok {
		r0 = rf(title, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]data.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(title, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTodo provides a mock function with given fields: id, album
func (_m *ITodoService) UpdateTodo(id int, album data.Todo) (*data.Todo, error) {
	ret := _m.Called(id, album)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *data.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int, data.Todo) (*data.Todo, error)); ok {
		return rf(id, album)
	}
	if rf, ok := ret.Get(0).(func(int, data.Todo) *data.Todo); ok {
		r0 = rf(id, album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int, data.Todo) error); ok {
		r1 = rf(id, album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITodoService creates a new instance of ITodoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITodoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITodoService {
	mock := &ITodoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
